title: Agile Au Fait
author: celestenicolesmith
email: celestnicolesmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Agile, scrum, and other product management musings.

# social links
twitter_username: AgileAuFait # DO NOT include the @ character, or else the build will fail!
github_username:  celestenicolesmith # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
